server:
  port: 8080
  include-message: always
  include-binding-errors: always
  include-stacktrace: on_trace_param
  include-exception: false

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service_product
    username: postgres
    password: admin

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      root: ERROR
      org.springframework: ERROR
      org.springframework.web: ERROR
      org.hibernate: ERROR

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8099/eureka/